apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .ClusterID }}
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: demo-eu-west-1a
  namespace: openshift-machine-api
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .ClusterID }}
      machine.openshift.io/cluster-api-machineset: demo-eu-west-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .ClusterID }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: demo-eu-west-1a
    spec:
      providerSpec:
        value:
          ami:
            id: ami-08b6d57cc42948927
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          iamInstanceProfile:
            id: {{ .ClusterID }}-worker-profile
          instanceType: m4.medium
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: eu-west-1a
            region: eu-west-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - {{ .ClusterID }}-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - {{ .ClusterID }}-private-eu-west-1a
          tags:
          - name: kubernetes.io/cluster/{{ .ClusterID }}
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""

